marketing_analytics_demo:
 target: dev
 outputs:
   dev:
     type: databricks
     method: http
     schema: "mkt_tahirfayyaz_prod"
     threads: 8
     host: "{{ env_var('DBT_HOST') }}"
     http_path: "sql/protocolv1/o/{{ env_var('DBT_ORG_ID') }}/{{ env_var('DBT_CLUSTER_ID') }}"
     token: "{{ env_var('DBT_ACCESS_TOKEN') }}"